apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: descaler-controller
  name: descaler-controller
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - watch
  - list
  - update
- apiGroups:
  - external.metrics.k8s.io
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: descaler-controller
  name: descaler-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: descaler-controller
subjects:
- kind: ServiceAccount
  name: descaler-controller
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: descaler-controller
  name: descaler-controller
